### ISSUE TITLE
Miner says "asterioid out of range"

### ISSUE THREAD

**Issue by MinaTheLoli** [Arcitectus/Sanderling#17]
Hello, i tryd the bot yesteda and it works very well, but today, i tryd it again and thebot will also do anything but than it comes to approching an teh miner detect that th asteroid is out of range. o the bot does approching, but again and again in an endles  lopp, after osme time teh ship is ca 100m away from the asteroid, the bot still says out of disctance aand does.... nothing

**Comment by Viir** [comment]
Closing issue to reduce noise with default view on github. It will be reopened when it is of interest to @MinaTheLoli again.

**Comment by advocaite** [comment]
i think he means the bot sometimes just clicks aproaching over and over

and when this happens it starts a endless loop

**Comment by MinaTheLoli** [comment]
thats why i mean
