### ISSUE TITLE
Do you know  how to set "miningsitebookmark"

### ISSUE THREAD

**Issue by epsilon201** [Arcitectus/Sanderling#19]
Hello,

i have a problem fitting`
 string[] SetMiningSiteBookmark = new[] {
	"beltl1"}
` with the right words.

belt1/belt/personal location do not work

**Comment by Viir** [comment]
> belt1/belt/personal location do not work

Why do you think this?

**Comment by Viir** [comment]
Closing issue to reduce noise with default view on github.
