### ISSUE TITLE
Sending a Directional Scan hotkey while game client window is in background

### ISSUE THREAD

**Issue by ALERTua** [Arcitectus/Sanderling#2]
Last patch they added this security feature: client ignores directional scan hotkey sent to a game client that is not focused. Before this feature, I noticed such behavior while sending mouse clicks via
WindowPostMessage(WM_LBUTTONDOWN, MK_LBUTTON, (y_coord << 16) | x_coord)
Now this. Maybe you can find the way to send directional scan hotkey and\or mouse clicks to game client that is at background? that would be lovely.
As a temporary workaround, one can focus on game client, send a hotkey or click, and focus on previous window, but typing texts while window focus jumps is annoying.

**Comment by ALERTua** [comment]
if you need any additional information — let me know.

**Comment by Arcitectus** [comment]
> Maybe you can find the way to send directional scan hotkey and\or mouse clicks to game client that is at background? that would be lovely.
As a temporary workaround, one can focus on game client, send a hotkey or click, and focus on previous window, but typing texts while window focus jumps is annoying.

At the moment it seems the best option is to contain both applications in an VMWare instance or a windows remote desktop session.
So far it seems that investing into imlementing this into Sanderling will not be worth the effort.

**Comment by ALERTua** [comment]
Then I guess they succeeded in securing clicks and keypresses from macro runners :) for now :)
thanks anyway

**Comment by Viir** [comment]
The focus issue can be solved by using remote desktop sessions as explained in the forum at http://forum.botengine.de/t/multi-instances-support/326

You can use multiple remote desktop sessions to have multiple bots make inputs at the same time.
