### ISSUE TITLE
Script to warp to 0 stopped working - Entry array in the menu is empty?

### ISSUE THREAD

**Issue by exodus444** [Arcitectus/Sanderling#23]
Looks like something is wrong with reading Entry array of the Menu. Due to which travel script is not working anymore - it just opens the menu and spams "no suitable menu entry found."

See screenshot of the API Explorer:

![menuentrynotrecognized](https://cloud.githubusercontent.com/assets/158017/26521946/92fcd2ae-42f5-11e7-9e7d-47d25ee8fcac.png)

**Comment by exodus444** [comment]
Hmm... today it's working fine once again. Not sure what it was that it stopped working yesterday. Closing the issue until it is reproduced again and I can provide conditions...

**Comment by Viir** [comment]
Thank you for updating this.
I think following questions could be of interest when narrowing down on the possible causes:
+ Does restarting the Sanderling Process make a difference?
+ Does restarting the eve online client make a difference?

**Comment by exodus444** [comment]
Neither one was making any difference. Closed everything, put PC into sleep mode for the night and this morning it was working fine again.

**Comment by Viir** [comment]
In such a case (API explorer shows unexpected values), check whether the issue can be reproduced using a sample of the eve online client process.
+ To obtain a sample of the eve online client process, follow the guide at http://forum.botengine.de/t/collecting-samples-for-memory-reading-development/50
+ Next, feed the process sample to the test method `Demo_memory_reading_from_process_sample` in this repository by adapting the `sampleFilePath` in the test setup to the file containing the process sample.
+ When executing the test, you should find in the `memoryMeasurement` variable the contents read from the process sample as they would appear in the Sanderling API Explorer.
