### ISSUE TITLE
Mining Bot

### ISSUE THREAD

**Issue by Hossi90** [Arcitectus/Sanderling#24]
Hey

Ich habe momentan ein Problem mit dem Miningbot. Die Tage hatte er wunderbar funktioniert ohne das er irgend ein Problem gemacht hat jedoch heute spinnt er total rum. Er warpt sich zum belt und sucht seine Astros, dass funktioniert soweit noch, jedoch fliegt er immer näher an den Astroiden ran aber schaltet ihn nicht auf und sagt die ganze Zeit, dass der Astro zu weit weg wäre, was absolut nicht stimmt da er schon nur noch 100 Meter vor ihm steht. Das skript ist unverändert und er spinnt erst seit heute rum.

Wäre dankbar für eine Antwort

Grüße

**Comment by Viir** [comment]
Was steht im Skript Log?

**Comment by Hossi90** [comment]
Danke für die schnelle Antwort. Hat sich von selbst erledigt, warum auch immer. Ging paar Stunden auf einmal wieder ohne das ich was verändert habe ^^

**Comment by Viir** [comment]
> Hat sich von selbst erledigt

In dem Fall mache ich das hier zu.
