### ISSUE TITLE
System.OutOfMemoryException after typing a "." after some object.

### ISSUE THREAD

**Issue by rremnar** [Arcitectus/Sanderling#26]
I have 6gb of ram, 4 is used up, so I am not out of memory. However, sometimes when I type a . after an object like for example "Sanderling." and the list of things tries to drop down I get a big window full of errors. Ontop it says:

{Type:"System.OutOfMemoryException",Message:"Insufficient memory to continue the execution of the program.",InnerException:null,StackTrace:"   at System.Runtime.InteropServices.Marshal.AllocHGlobal(IntPtr cb)

The exception error is saved to a text file.
[2017.05.17.00.40.39 Exception.txt](https://github.com/Arcitectus/Sanderling/files/1082958/2017.05.17.00.40.39.Exception.txt)

I've been getting a lot of these throughout the time I am writing code in Sanderling.

My PC stats: Windows 10 Pro, i3 3.1gz dual virtualized core, 6gb ram, Radeon HD 4650 512mb vid card, 250gb HDD

Programs Opened: Windows Explorer, Google Chrome, Notepad++, Paint.net, Eve game, Sanderling

**Comment by Viir** [comment]
It looks like there are peaks in memory usage which make it exhaust the 32 bit memory address space.

One way to go about this would be to increase the amount of addressable memory by running the sanderling executable as 64 Bit process. I remember that some of the functions to interface with Windows API where not implemented yet for use in a 64 Bit process. So a switch to 64 Bit might need some additional implementation.

**Comment by Viir** [comment]
I created a new release to test the 64 Bit version. You can download it at https://github.com/Arcitectus/Sanderling/releases/tag/v17.05.18

Do you see any issues with version 17.05.18?

**Comment by Viir** [comment]
Closing this since the issue did not appear anymore after switching to version 17.05.18.
