### ISSUE TITLE
Error on parse when using mining script

### ISSUE THREAD

**Issue by ChrisDevinePimss** [Arcitectus/Sanderling#28]
[
  {
    "TimeDateTimeIntraDayCal": "22.20.00",
    "TimeDateTimeIntraSecMilliString": "474",
    "CaptionString": "System.Exception: compilation error: (67,1): error CS1529: A using clause must precede all other elements defined in the namespace except extern alias declarations\r\n   at BotSharp.ScriptRun.ScriptRun.<>c__DisplayClass61_0.<Start>b__0()",
    "LineIndex": 66,
    "CharacterIndexInLine": 33,
    "LineIndexInAvalonEdit": 67,
    "CharacterIndexInLineInAvalonEdit": 34
  }
]

**Comment by Viir** [comment]
To resolve this error, move the using directive from line 66 to the top of the script.

For more details, on this error see https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs1529
