### ISSUE TITLE
Drones are not docked when retreating

### ISSUE THREAD

**Issue by tetreum** [Arcitectus/Sanderling#32]
When retreat mode is started, there is no attempt to dock in space drones, leaving them behind:
https://github.com/Arcitectus/Sanderling/blob/master/src/Sanderling/Sanderling.Exe/sample/script/Mine.ore.cs#L82

I understand that retreat usually means emergency exit, but i'm experiencing the execution of retreat mode while in sec space & having the drones in fight against simple npcs.
Maybe we could add another config var like `bool returnDronesToBayOnRetreat = false`. If true, it would fire `DroneEnsureInBay();` before executing `InitiateDockToOrWarpToBookmark(RetreatBookmark);`

**Comment by Viir** [comment]
I do not yet understand completely and have a question:

> but i'm experiencing the execution of retreat mode while in sec space & having the drones in fight against simple npcs.

Is that behavior desireable in your case?

**Comment by tetreum** [comment]
When bot goes retreat mode, it doesn't attempt to return drones back to bay before jumping to retreat bookmark.

I usually experience retreat mode with no reason at all as my drones can easily destroy the NPCs, but i don't care about as usually it restores operations after a while.
What i don't like is that it leaves the drones in the asteroid belt when running away. That's why i made that PR :)
