### ISSUE TITLE
Mining script: Detect Cluster shutdown

### ISSUE THREAD

**Issue by tetreum** [Arcitectus/Sanderling#34]
It would be cool to detect the display of "Cluster Shutdown in..." and set it as retreat reason.
![http://i.imgur.com/yZ4hQNj.jpg](http://i.imgur.com/yZ4hQNj.jpg)

**Comment by Viir** [comment]
> It would be cool to detect the display of "Cluster Shutdown in..."

The text visible in the center of the screenshot is available in `AbovemainMessage`  property of the memory measurement.

Just in case anyone is wondering how to test this without having to wait for a shutdown: You can save a snapshot of the eve client process to inspect it later using the guide from http://forum.botengine.de/t/collecting-samples-for-memory-reading-development/50

**Comment by tetreum** [comment]
Thank you for the info!
Is there any way to attach an event listener? So i just check it whenever the message changes rather than setting an interval/loop?

**Comment by Viir** [comment]
> Is there any way to attach an event listener?

I don't know of an event listener.


> So i just check it whenever the message changes rather than setting an interval/loop?

How about doing such a check in the same place where the check for hitpoints happens? This way, the existing interval/loop would be reused.
