### ISSUE TITLE
Script editor: Focus to input on CTRL + F

### ISSUE THREAD

**Issue by tetreum** [Arcitectus/Sanderling#35]
When you press CTRL + F the Search window appears but without having the input focused.

Could it be possible to focus it by default? So you can make CTRL + F -> CTRL + V / start typing rather than CTRL + F -> Mouse click -> CTRL + V / start typing

**Comment by Viir** [comment]
I agree this behaviour would be desireable. I plan to look into this before I publish the next release.

**Comment by Viir** [comment]
@tetreum, I made a change with commit #d7caf6d to implement the improvement as you suggested.

With that change, the focusing worked correctly in my tests, so I close this issue.
