### ISSUE TITLE
Schiff stoppen

### ISSUE THREAD

**Issue by Hossi90** [Arcitectus/Sanderling#37]
Hallo!

Gibt es eine Möglichkeit, dass das Schiff anhält wenn die miner an sind? Er fliegt bei mir immer gegen astros und bugt sich dort fest, weil er sich immer weiter dem Astro nähert.

Grüße

**Comment by Viir** [comment]
Wie wäre es mit folgender Möglichkait:
Klicken auf den Stop button im Ship UI wenn die Distanz zu allen Targets kleiner ist als die Miningdistanz.

Siehst du ein Problem mit dieser Möglichkeit?

**Comment by Hossi90** [comment]
Nein kein Problem ^^ hatte mehr die Befürchtung, dass ich dadurch im sanderling irgend ein Befehl durcheinander bringe, wenn ich dort manuell noch rumfummel.
Danke :)
