### ISSUE TITLE
Compilation error: Ambiguous MainStep

### ISSUE THREAD

**Issue by raoulkent** [Arcitectus/Sanderling#39]
After editing SetMiningSiteBookmark, UnloadBookmark & RetreatBookmark to test bookmarks in-game - then attempting to Play the script I get a error as follows:

`    "CaptionString": "System.Exception: compilation error: (64,29): error CS0121: The call is ambiguous between the following methods or properties: 'MainStep()' and 'MainStep()'\r\n   at BotSharp.ScriptRun.ScriptRun.<>c__DisplayClass61_0.<Start>b__0()",
    "LineIndex": 63,
    "CharacterIndexInLine": 28,
    "LineIndexInAvalonEdit": 64,
    "CharacterIndexInLineInAvalonEdit": 29`

**Comment by Viir** [comment]
This looks like a compilation error, indicating that the script is not valid C#. Do you have a link to a diff view with the file from https://github.com/Arcitectus/Sanderling/blob/master/src/Sanderling/Sanderling.Exe/sample/script/Mine.ore.cs as base?

**Comment by Viir** [comment]
Do you have more than one `MainStep` methods in your script?

**Comment by raoulkent** [comment]
Ah, I identified the issue. I had imported the code twice, resulting in duplicates of all function names, therefore causing a ambiguity problem.

After clearing the 'edit script' area and re-importing everything is working fine.
