### ISSUE TITLE
Focus modules on one asteroid?

### ISSUE THREAD

**Issue by admruul** [Arcitectus/Sanderling#41]
the mining bot works great but for some reason it only focuses on one asteroid while the other one stays offline. I was wondering if it’s possible to set up the bot so that both modules focus one?

In the log it says “asteroid distance too far” or something along those lines and keeps going towards the current asteroid with only one module.

How can this be setup to work with both modules active on the same asteroid?? Thanks

**Comment by Viir** [comment]
The first idea that comes to mind is to look at the change which was made to make the bot uses only one mining module per asteroid.
Starting with that change might be the easiest way to figure out to change it back to use all modules on one asteroid.
You can see that change at: https://github.com/Arcitectus/Sanderling/commit/b4264d3944141c627d7efd234b8a4c56d69f1aaf#diff-e9db94da9819a4c159ad43027f44130e

What do you think of this approach?

**Comment by Viir** [comment]
Looks like this has been answered at http://forum.botengine.de/t/mining-bot-only-one-laser/574
