### ISSUE TITLE
MouseDoubleClick method not working, as the delay is too long

### ISSUE THREAD

**Issue by testeaxeax** [Arcitectus/Sanderling#44]
The delay between two mouse clicks is too long for a double click to be detected as one, instead it gets detected as two single clicks.
The constant defining the delay:
https://github.com/Arcitectus/Sanderling/blob/f4fdaef1f6ed1d4b8c490f3f74616963d28e295b/src/Sanderling/Sanderling/Motor/WindowMotor.cs#L16

I found out that a delay of 120 ms is enough for a double click to work.

**Comment by Viir** [comment]
Thank you for sharing this and the PR.
