### ISSUE TITLE
 cargo hold instead of the ore hold

### ISSUE THREAD

**Issue by daveshomedenham** [Arcitectus/Sanderling#47]
does anyone know how to change the script so it choses the cargo hold instead of the ore hold Michael Rätzel said it can be done

**Comment by tetreum** [comment]
Please, try looking for yourself through the code, it's not hard, you're just lazy.

**Comment by daveshomedenham** [comment]
Yes did it ages ago and you're ugly but I can stop being lazy and your
always be ugly especially inside
