### ISSUE TITLE
32bit build?

### ISSUE THREAD

**Issue by ramonskie** [Arcitectus/Sanderling#55]
is it possible to also build a 32bit build?
so ppl on linux can also use it.

this is due to the fact that dot.net does not work with wine 64bit. and probably never will.

**Comment by Viir** [comment]
Yes, you can do that.

I dug around a little bit and found a guide on how to do this at https://forum.botengine.de/t/sanderling-app-release-march-2018/808/9?u=viir

**Comment by ramonskie** [comment]
thanks will try this this.
hope i can find visual studio somewhere

**Comment by Viir** [comment]
> this is due to the fact that dot.net does not work with wine 64bit. and probably never will.

If you want to test your setup without the need to build yourself or use visual studio, you can download binaries from an older release here on github.
It looks like the first release after switching to a 64 Bit Build was https://github.com/Arcitectus/Sanderling/releases/tag/v17.05.18

For example, when I run the binary from [release v17.05.03](https://github.com/Arcitectus/Sanderling/releases/tag/v17.05.03), task manager says it is `32 bit`.
