### ISSUE TITLE
LabelText[] of Ship hangar contains very wide IUIElementText

### ISSUE THREAD

**Issue by asdfasdf100500** [Arcitectus/Sanderling#6]
Hello

If I take Ship hangar view from WindowOther and look at its LabelText array, I can see IUIElementTexts that have a Max0 of 3000+. MouseClicking these result in bringing applications next to Eve Window to foreground.

Same issue is somehow worked around in WindowInventory.SelectedRightItem.ListView.Entry (which have a Max0 of 1000+). Entry.LabelText[] still contains very wide label.

Can something be done to these wide labels in inventory screens? I suspect they are not parsed incorrectly and are just very wide in EVE. How is the issue worked around in SelectedRightItem.ListView.Entry?

Thanks for the awesome framework!

Br. Asdfasdf

**Comment by Arcitectus** [comment]
I have a question to make sure we are actually looking at the same thing:

>If I take Ship hangar view from WindowOther

I am not sure if there are any other views of Ship hangar than the one I found.

I looked for a 'Ship hangar' view and this is the closest I came up with:
I rightclicked on the "Ship hangar" Tree Entry in an `WindowInventory` and then clicked on "open in new window" in the opening menu. This way I got a new window, which showed up in `WindowOther`. To me, this one looks like any other inventory window so far, except the caption:
- on the left, I can enable the tree view to select a container.
- on the right I am shown items contained in the selected container.
- I can apply the 'List' view on the selected containers items.

Does this apply to the Ship hangar view you are seeing as well?

**Comment by asdfasdf100500** [comment]
I do think you have the right window. It looks like any other inventory window and it behaves as you described.

The way I opened mine was from the top left main menu -> Inventory -> Open Ship Hangar

**Comment by Arcitectus** [comment]
That window should be show up as an `IWindowInventory` in the API. This is a bug I did not notice before.


> Can something be done to these wide labels in inventory screens?

Since you write
> Same issue is somehow worked around in WindowInventory.SelectedRightItem.ListView.Entry

I assume offering the corresponding `IListEntry` at the API will be sufficient to solve your problem.
I will publish a new release to fix this.

> How is the issue worked around in SelectedRightItem.ListView.Entry?

I don't think there is a workaround since those are different nodes in the UI tree. In this case the child node is simply larger than its parent.

**Comment by Arcitectus** [comment]
I tested this with release v16.04.18 and that worked on my end. It showed me the entries in the Ship hangar.

**Comment by asdfasdf100500** [comment]
Yup, works.

Thank you for your effort!
