### ISSUE TITLE
Why does pressing ctrl + alt cause the robot to pause?

### ISSUE THREAD

**Issue by NimaQu** [Arcitectus/Sanderling#62]
It conflicts with my screenshot shortcuts, so the bot will automatically pause when I take a screenshot, how can I turn it off?

**Comment by Viir** [comment]
Thank you for the feedback.
The `CTRL` + `Alt` keyboard command can be turned off by removing the entries here:
https://github.com/Arcitectus/Sanderling/blob/06d196a66777bfd8313d6e36bc7f2925a2a7c840/src/Sanderling/Sanderling.Exe/App.UI.cs#L20-L24
And then rebuild the App in Visual Studio.

**Comment by NimaQu** [comment]
Thanks !
