### ISSUE TITLE
unsuppot 64-bit game client

### ISSUE THREAD

**Issue by NimaQu** [Arcitectus/Sanderling#63]
It can't find the process

**Comment by Viir** [comment]
> It can't find the process

Is this related to Sanderling at all?

**Comment by NimaQu** [comment]
> > It can't find the process
> 
> Is this related to Sanderling at all?

yes , it cant select 64bit game clinet

**Comment by Viir** [comment]
> > > It can't find the process
> > 
> > 
> > Is this related to Sanderling at all?
> 
> yes , it cant select 64bit game clinet

How is this related to Sanderling? Where do you see 'select 64bit game clinet' in Sanderling or in this repository? Do you have a screenshot to illustrate what you are seeing? A video would work too.

**Comment by NimaQu** [comment]
![img](https://i.loli.net/2019/06/11/5cff9de1386ca66013.png)
If I run the game client as 64-bit, I can't find the correct process in Sanderling and cant select it

**Comment by Viir** [comment]
Thank you for the clarification @NimaQu, now I can follow.

I have a question about the `Run clients with 64 bit` checkbox visible in the screenshot: Do you see any problems with disabling this option?
Is the 64-bit game client the only one available to you?

**Comment by NimaQu** [comment]
Thanks，Using a 32-bit client doesn't currently affect it, but I think one day ccp will give up the 64-bit client.I will try to solve it

**Comment by Viir** [comment]
If you see any indication that CCP will phase out the client that works for us now (32-bit client), that would be something I can look into.

**Comment by Viir** [comment]
Support for the 64-bit game client was implemented in January.
