### ISSUE TITLE
button undock not work

### ISSUE THREAD

**Issue by bozoweed** [Arcitectus/Sanderling#64]
hello when bot try to undock that not work everthing work but not undocking button

**Comment by Viir** [comment]
Have you seen these instructions: https://forum.botengine.org/t/mining-bot-wont-undock/2560/5?u=viir ?
Are these detailed enough to make it work for you?

**Comment by bozoweed** [comment]
i have using an other way its juste for tell to dev the native sanderling function is not working for found the undock buttion and from past it's work like charmed

**Comment by Viir** [comment]
Thank you for the feedback!

**Comment by Viir** [comment]
We recently updated the default mining bot to fix the undocking problem. It now undocks automatically again. The newest version of the mining bot is at https://github.com/Viir/bots/blob/master/guide/eve-online/how-to-automate-mining-asteroids-in-eve-online.md

Also, the list at https://forum.botengine.org/t/list-of-eve-online-bots-for-beginners/629 links the EVE Online bots which are best tested and easy to set up.
