### ISSUE TITLE
32 bit eve client deprecated 

### ISSUE THREAD

**Issue by MrBiz** [Arcitectus/Sanderling#67]
I remember it being said that Sanderling wouldn't be made 64 bit compatible until eve 32bit client was deprecated,(https://github.com/Arcitectus/Sanderling/issues/63)

Well it appears to have happened. 

https://www.eveonline.com/article/q6b32b/32-bit-client-deprecation

still nice work.

**Comment by Viir** [comment]
I have good news for you: We now use Sanderling with the 64-bit client.

I updated the thread you linked.

**Comment by MrBiz** [comment]
Full of good news!
