### ISSUE TITLE
Could you please tell me how to build readmemory64 in detail?

### ISSUE THREAD

**Issue by R4M80MrX** [Arcitectus/Sanderling#68]
win10 64bit
.net sdk 3.1
run build.bat
run read-memory-64-bit.exe in \read-memory-64-bit\obj\x64\Debug\netcoreapp3.1
get `A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 'C:\Program Files\dotnet'.`

**Comment by R4M80MrX** [comment]
btw, how can I join discord to discuss with you? I'm an old player and I want to contribute to this project

**Comment by Viir** [comment]
To build I use the script at https://github.com/Arcitectus/Sanderling/blob/master/implement/read-memory-64-bit/build.bat

The last time for the last release, so just a few days ago. I don't remember installing a new version of .NET core in the meantime, here are the dotnet versions I see on the machine I used to build:
```
PS C:\Users\John> dotnet --version
3.1.201
PS C:\Users\John> dotnet --list-sdks
[...]
3.0.100 [C:\Program Files\dotnet\sdk]
3.1.101 [C:\Program Files\dotnet\sdk]
3.1.201 [C:\Program Files\dotnet\sdk]
```

> how can I join discord to discuss with you?

Regarding the Sanderling project, the best matching discord server I know is at https://to.botengine.org/discord

**Comment by R4M80MrX** [comment]
Thank you for your reply. I've joined this discord server serveral days ago~
