### ISSUE TITLE
Module overload indicator possible?

### ISSUE THREAD

**Issue by asdfasdf100500** [Arcitectus/Sanderling#7]
Hello!

Awesome piece of software as usual. It's really gotten me hooked on EVE again! :)

Would it be possible to parse the module overload/heat indicator? Little green rectangle above the module

Br. asdfasdfasdf100500

**Comment by Arcitectus** [comment]
I took a look at it. I guess that would be an additional member of type `bool` on the module. Is that what you had in mind?

**Comment by asdfasdf100500** [comment]
Yup, exactly like that

**Comment by Arcitectus** [comment]
I added `null` as a third possible value to the model to signify for example when the reading for this part fails.
The next release will add support for this member, but that implementation will depend on english localization.

**Comment by Arcitectus** [comment]
This feature is available with release v16.05.21: https://github.com/Arcitectus/Sanderling/releases/tag/v16.05.21
