### ISSUE TITLE
Broken info link & can't apply --session-length-limit

### ISSUE THREAD

**Issue by tetreum** [Arcitectus/Sanderling#70]
Not sure if this is the proper repo, because i couldn't find that link in bots & sanderling source codes.

I'm getting this message, whose link is broken:
> Session  finished: Reached maximum duration for offline session of 15 minutes. To run the app in a longer session, start an online session. For more information, continue at https://to.botengine.org/from-console-reached-maximum-duration-of-offline-session

Is this the right link? https://github.com/Viir/bots/blob/master/guide/botengine-online-session.md

I've tried applying `--session-length-limit` param to miner's bat file like this: `botengine.exe run --session-length-limit=86400   https://github.com/Viir/bots/tree/a8b89533c2e6d06aef48bc44f20a71c987bb73ed/implement/applications/eve-online/eve-online-mining-bot`
But i'm still getting that message :s

**Comment by Viir** [comment]
Thank you for the feedback!
I will repair that link.
Yes, the best guide on that topic I see is https://github.com/Viir/bots/blob/master/guide/botengine-online-session.md

Seeing this issue, I see I can improve the botengine.exe program to display a warning or error for this combination of parameters:
In this case you need to add the `--online-session` option, so the complete command will be:
```
botengine.exe run  --online-session  --session-length-limit=86400 https://github.com/Viir/bots/tree/a8b89533c2e6d06aef48bc44f20a71c987bb73ed/implement/applications/eve-online/eve-online-mining-bot
```

**Comment by tetreum** [comment]
Oh, when using the configure script button at:
https://catalog.botengine.org/63d2b10af9b7b7001c49cfc3eb63888b6905aa50fe18a4cb99caadd5cfcc4249/configure-run-app/eyJvbmxpbmVTZXNzaW9uIjpmYWxzZSwiYXBwU2V0dGluZ3MiOiIiLCJwYXVzZUFwcEtleXMiOiIiLCJzZXNzaW9uTGVuZ3RoTGltaXQiOiIzMjQyIn0=

If you type in session-length-limit , it does not add the online-session one, so seemed optional

**Comment by Viir** [comment]
Right, that script configuration interface can be improved to be consistent with the error you would get from the (next version of the) botengine.exe.

> But online sessions are paid right? So now it's only a 15min trial.

Right. There is a pricing page at https://www.botengine.org/pricing

About payment: When you create the account you get enough credits for 30 minutes app run time. If these are used up, the botengine.exe should give you a specific message that credits are used up.

**Comment by tetreum** [comment]
Don't worry i hardly play Eve, i'm just an alpha account. I like more the "hacking"/automating part xD

Hope business goes well to you!

**Comment by Viir** [comment]
Good to know, thank you again. In case you change your mind, the offer still stands.

**Comment by Viir** [comment]
I published version 2020-06-27 of the botengine.exe program to prevent such a confusion in the future: https://github.com/Viir/bots/commit/6f88c0f03187e71a22a06b25c2e393c8873a0b8b
This version emits an error message in case of inconsistent use of session length limit argument and online session option:

```
There is a problem with the given arguments: The configured session length limit of 123 minutes is larger than the general limit for offline sessions (15 minutes).
To configure a limit of 123 minutes, enable the '--online-session' option too.
For more information, continue at https://to.botengine.org/guide/online-session
```

**Comment by tetreum** [comment]
Nice, now it's easier to understand what's happening!
