### ISSUE TITLE
speedup finding UIRoot

### ISSUE THREAD

**Issue by antan77** [Arcitectus/Sanderling#71]
It tooks round about 4min and 16GB of Ram to find the UiRoot-Address(largest). How can i speed up this?

**Comment by Viir** [comment]
I found some instructions on speeding it up at https://forum.botengine.org/t/help-with-read-memory-64-bit-exe/3398/6?u=viir

> Good point about the timing. There is more to this: There different ways to use the `read-memory-eve-online` command, and there is a huge difference in the time needed.
> If you use the command in the simplest way, it must search for the root of the UI tree first. To quote the help text from the tools user interface:
> 
> > If the address is not specified, the program searches the whole process memory for UI roots.
> 
> If you want it to complete in less than a second, tell it the UI tree's root address, so it does not have to search it first. Use the `--root-address` option like this: `--root-address=0x27891CEBC50`.
> If you let it search the whole process, it will tell you the UI tree root addresses it has found so that you can reuse them later.
> 
> AFAIR, when you read from a sample file, it still takes longer than a second. That route is not as optimized as reading from a live process.
>

**Comment by Viir** [comment]
I see multiple ways to speed this up:

+ Use less memory in the game client process.
+ Use the same route that popular apps use, these seem to take about 10 seconds to find the UI root. AFAIR these apps read from a live process, not from a sample file.
+ Optimize the program code for your scenario.

I found this at https://forum.botengine.org/t/help-with-read-memory-64-bit-exe/3398/6?u=viir

> AFAIR, when you read from a sample file, it still takes longer than a second. That route is not as optimized as reading from a live process.
>

**Comment by antan77** [comment]
I am really sorry, I do'nt told you that I know about specifying the uiroot-address. My Problem is, I dont know how to find it.

I tried with cheat engine and pointerscan, but the result is not very satisfying.

**Comment by R4M80MrX** [comment]
> I am really sorry, I don't told you that I know about specifying the uiroot-address. My Problem is, I dont know how to find it.
> 
> I tried with cheat engine and pointerscan, but the result is not very satisfying.

Can I have your contact information？

**Comment by antan77** [comment]
For sure, i am martin, antan77@knowing.email <mailto:antan77@knowing.email> 

 

Regards

 

martin

 

Von: R4M80MrX <notifications@github.com> 
Gesendet: Sonntag, 9. August 2020 04:52
An: Arcitectus/Sanderling <Sanderling@noreply.github.com>
Cc: antan77 <antan77@knowing.email>; Author <author@noreply.github.com>
Betreff: Re: [Arcitectus/Sanderling] speedup finding UIRoot (#71)

 

I am really sorry, I don't told you that I know about specifying the uiroot-address. My Problem is, I dont know how to find it.

I tried with cheat engine and pointerscan, but the result is not very satisfying.

Can I have your contact information？

**Comment by Viir** [comment]
> I am really sorry, I don't told you that I know about specifying the uiroot-address. My Problem is, I dont know how to find it.
> 
> I tried with cheat engine and pointerscan, but the result is not very satisfying.

To find the address of the UIRoot, use the `read-memory-64-bit.exe` program with the command to read from an EVE Online process. As far as I remember, the command is named `read-memory-eve-online`. What is the list of commands that you see in the help text for the program?
You can use the `--pid` option to give it the ID of a live game client process.

**Comment by antan77** [comment]
Hey Mike,

 

very good hint, I can scan for uiroot now in 15s. Its very awesome now, thank you very much.

 

I ve now my own bot with c# and can do nearly everything regarding the ui.

 

THX again

 

Martin

 

Von: Michael Rätzel <notifications@github.com> 
Gesendet: Dienstag, 11. August 2020 11:55
An: Arcitectus/Sanderling <Sanderling@noreply.github.com>
Cc: antan77 <antan77@knowing.email>; Author <author@noreply.github.com>
Betreff: Re: [Arcitectus/Sanderling] speedup finding UIRoot (#71)

 

I am really sorry, I don't told you that I know about specifying the uiroot-address. My Problem is, I dont know how to find it.

I tried with cheat engine and pointerscan, but the result is not very satisfying.

To find the address of the UIRoot, use the read-memory-64-bit.exe program with the command to read from an EVE Online process. As far as I remember, the command is named read-memory-eve-online. What is the list of commands that you see in the help text for the program?
You can use the --pid option to give it the ID of a live game client process.

**Comment by antan77** [comment]
Hey Mike,

 

if you have time, can you give me a hint?

 

I am continuously read mem with getmem. But if I quit the game, I get different exceptions cause of non-valid memory.

 

Any idea how to catch this “all-in-one”?

 

Best regards 

 

Martin

 

Von: Michael Rätzel <notifications@github.com> 
Gesendet: Dienstag, 11. August 2020 11:55
An: Arcitectus/Sanderling <Sanderling@noreply.github.com>
Cc: antan77 <antan77@knowing.email>; Author <author@noreply.github.com>
Betreff: Re: [Arcitectus/Sanderling] speedup finding UIRoot (#71)

 

I am really sorry, I don't told you that I know about specifying the uiroot-address. My Problem is, I dont know how to find it.

I tried with cheat engine and pointerscan, but the result is not very satisfying.

To find the address of the UIRoot, use the read-memory-64-bit.exe program with the command to read from an EVE Online process. As far as I remember, the command is named read-memory-eve-online. What is the list of commands that you see in the help text for the program?
You can use the --pid option to give it the ID of a live game client process.

**Comment by R4M80MrX** [comment]
auto python27Dll = findModule(L"python27.dll", processId, errorMessage);
auto typeObjectAddress = (DWORD64)python27Dll.modBaseAddr + 0x5223C0;
