### ISSUE TITLE
how is the read-memory project used?

### ISSUE THREAD

**Issue by GitMyCode** [Arcitectus/Sanderling#73]
Hi! I really like what was done in this project. i didn't know elm but i do appreciate his functional aspect!

I want to understand how all this is wired. When we run the alternate-ui project how is it using the c# code? i see VolatileHostScript that has a string of a c# script that resemble what is in the read-memory project. How is the information of the c# memory reading passed to the elm?
I would like to use your memory-reading c# for a small app in c#. Is it possible to use it as a library?

**Comment by Viir** [comment]
> When we run the alternate-ui project how is it using the c# code? i see VolatileHostScript that has a string of a c# script that resemble what is in the read-memory project.

The volatile host supports C# script as a source by default. The source code for the volatile host lives in the Elm Fullstack repository: https://github.com/elm-fullstack/elm-fullstack/blob/594cf52319e72cb28230bbe1ec9a9198d2d6b6c4/implement/elm-fullstack/Pine/VolatileHost.cs

> How is the information of the c# memory reading passed to the elm?

Communication between the volatile host and the Elm app currently works by exchanging String values. One String for the request and one String for the response.
In alternate UI, the reading from the game client is serialized in the same format that you get when you let the CLI write the reading to a file.

> I would like to use your memory-reading c# for a small app in c#. Is it possible to use it as a library?

You can use it as a library using the same .NET assembly file that the alternate UI uses.

**Comment by GitMyCode** [comment]
Thanks a lot! 
but when you say the alternate UI use the `read-memory-64-bit.dll` i don't really see where. or maybe you mean that the alternate-ui use a stringified version of the read-memory in `..Sanderling\implement\alternate-ui\source\src\EveOnline\VolatileHostScript.elm` ?

**Comment by GitMyCode** [comment]
ho nevermind i get it :)
