### ISSUE TITLE
Windows XP support

### ISSUE THREAD

**Issue by asdfasdf100500** [Arcitectus/Sanderling#8]
Hello

I'm trying to run Sanderling in Windows XP environment. I use XP because it supports hardware serial signature sproofing.

Unfortunately Sanderling crashes on startup: "16.06.23.Sanderling.exe has encountered a problem and needs to close."

I suspect it is because XP does not support .NET 4.6.

It however supports .NET 4.0. Do you think it would be possible to compile Sanderling using .NET 4.0?

If you need something rewritten, I'm more than willing to help

Br. Number one Sanderling fan

**Comment by Viir** [comment]
I think it is unlikely that you can make it work with .NET version <= 4.0.
You would have to replace the libraries it depends on. The executable project with the IDE, depends probably on at least the ones listed at [https://github.com/Arcitectus/Sanderling/blob/master/src/Sanderling/Sanderling.Exe/packages.config](https://github.com/Arcitectus/Sanderling/blob/master/src/Sanderling/Sanderling.Exe/packages.config)

I observed a problem with one of the `Microsoft.CodeAnalysis` [(roslyn)](https://github.com/dotnet/roslyn) ones that was resolved by switching to .NET 4.6.1 [(http://forum.botengine.de/thread/sanderling-release-version-15-11-11/?order=all#comment-84587835-8665-4849-bc84-a57000f621a9)](http://forum.botengine.de/thread/sanderling-release-version-15-11-11/?order=all#comment-84587835-8665-4849-bc84-a57000f621a9)

**Comment by asdfasdf100500** [comment]
Thank you. I tried playing with the source code but couldn't make it work. Guess I'll have to find another way to bot :-)
