### ISSUE TITLE
High memory consumption during root search

### ISSUE THREAD

**Issue by ranc1** [Arcitectus/Sanderling#83]
Hello,
I have observed high memory usage (>10G) during root search using the command line when the PID is provided: `./read-memory-64-bit.exe read-memory-eve-online --pid {pid} --output-file {output_file}`. I believe this might be related to how the program samples the process during root search ([here](https://github.com/Arcitectus/Sanderling/blob/main/implement/read-memory-64-bit/Program.cs#L136)).
I took a stab at it to improve the memory usage by changing [these lines](https://github.com/Arcitectus/Sanderling/blob/main/implement/read-memory-64-bit/Program.cs#L129-L137) to:
```
if (processId.HasValue)
{
    var possibleRootAddresses = 0 < rootAddressArgument?.Length ? ImmutableList.Create(ParseULong(rootAddressArgument)) : EveOnline64.EnumeratePossibleAddressesForUIRootObjectsFromProcessId(processId.Value);

    return (new MemoryReaderFromLiveProcess(processId.Value), possibleRootAddresses);
}
```
it reduces the memory (<2G) as it does not "read content" when calling `ReadCommittedMemoryRegionsFromProcessId`.
This change also sped up the root search step by a little. Also, there is no longer dependency on the screenshots, so the command does not error even when the window is not focused.

**Comment by UNSC1419** [comment]
I recompiled according to your new code, and the memory usage has changed from 10G to 2G!!
nice!
