### ISSUE TITLE
Sanderling.WindowHandle returns zero

### ISSUE THREAD

**Issue by ALERTua** [Arcitectus/Sanderling#9]
Sanderling.WindowHandle returns zero. It has to return current WindowHandle of attached EVE Client Window.
I guess that Sanderling.WindowPostMessage, Sanderling.WindowPostMessageKeyDown and Sanderling.WindowPostMessageKeyUp also send messages to hWnd=0.

**Comment by Viir** [comment]
> It has to return current WindowHandle of attached EVE Client Window.

What do you mean with "attached EVE Client Window"?
