### ISSUE TITLE
Ability to read locked target  health?

### ISSUE THREAD

**Issue by igvr** [Arcitectus/Sanderling#90]
pythonObjectTypeName=="TargetHealthBars" and children seems to lack some kind of transform or additional sprites for 'red' semicircles?

**Comment by igvr** [comment]
tried adding some dict entry keys ... 
`    
    "armorBar": {
            "address": "2916128131504",
            "pythonObjectTypeName": "Container"
        },
        "hullBar": {
            "address": "2915784051904",
            "pythonObjectTypeName": "Container"
        },
`

is there more I need to modify to get more data from these containers?

**Comment by igvr** [comment]
found this:
`        "damageValuseForTooltip": {
            "address": "2914896395928",
            "pythonObjectTypeName": "dict"
        },`
        
but where values? ;(

**Comment by Viir** [comment]
> pythonObjectTypeName=="TargetHealthBars" and children seems to lack some kind of transform or additional sprites for 'red' semicircles?

Is this information present in the memory reading at all?

If we don't find it in the game client process memory, we could go the image processing route, as we did earlier for the button labels.

**Comment by igvr** [comment]
i tried diff'ing two dumps and couldnt find it(unless memreader C# code filters something out?)

**Comment by Viir** [comment]
The game client process memory often contains more than 1 gigabytes. The JSON representation is much smaller. Typically we filter more than 99% out. Have a look at <https://github.com/Arcitectus/Sanderling/blob/main/implement/read-memory-64-bit/Program.cs#L689> for the selection criteria.
